import type { ParsedDocument } from '@/types';

export const SAMPLE_DOCUMENTS: ParsedDocument[] = [
  {
    id: 'lease-001',
    title: 'Residential Lease Agreement',
    subtitle: 'Confidential // 12-Month Tenancy — Unit 4B, Maple Court',
    category: 'property',
    detected_roles: ['tenant', 'landlord', 'co-signer'],
    clauses: [
      {
        id: 'c1',
        clause_ref: '4.2',
        title: 'Late Rent Penalty',
        description: 'Rent is due on the 1st of each month. A late fee of $75 applies after the 3rd day, with an additional $15/day thereafter up to $500 maximum. This is a standard penalty structure, but the daily compounding rate is aggressive — some jurisdictions cap daily late fees.',
        risk_level: 'medium',
        source: { page: 3, clause_ref: '4.2' },
        relevant_to: ['tenant'],
        excerpt: 'If Tenant fails to pay rent within three (3) days of the due date, a late fee of seventy-five dollars ($75.00) shall apply, plus fifteen dollars ($15.00) per additional day, not to exceed five hundred dollars ($500.00) in total.',
      },
      {
        id: 'c2',
        clause_ref: '7.1',
        title: 'Security Deposit Deductions',
        description: 'The landlord may deduct from the security deposit for any damage beyond "normal wear and tear" without specifying what constitutes normal wear and tear. This is broadly worded and could allow the landlord to claim deductions for minor scuffs or aging.',
        risk_level: 'high',
        source: { page: 5, clause_ref: '7.1' },
        relevant_to: ['tenant', 'landlord'],
        excerpt: 'Landlord may deduct from the security deposit the cost of repairing any damage to the Premises beyond normal wear and tear, including but not limited to painting, cleaning, and replacement of fixtures.',
      },
      {
        id: 'c3',
        clause_ref: '9.3',
        title: 'Early Termination',
        description: 'The tenant may terminate early with 60 days written notice but forfeits one month\'s rent as a termination fee. The landlord has no corresponding early termination right listed, creating an asymmetry in flexibility.',
        risk_level: 'medium',
        source: { page: 7, clause_ref: '9.3' },
        relevant_to: ['tenant'],
        excerpt: 'Tenant may terminate this Lease prior to expiration upon sixty (60) days written notice to Landlord, and shall pay a termination fee equal to one (1) month\'s rent.',
      },
      {
        id: 'c4',
        clause_ref: '12.1',
        title: 'Maintenance Responsibility',
        description: 'Tenant is responsible for all repairs under $200 per incident. This shifts a broad range of minor repair costs to the tenant that would typically be the landlord\'s responsibility in many jurisdictions.',
        risk_level: 'low',
        source: { page: 9, clause_ref: '12.1' },
        relevant_to: ['tenant', 'landlord'],
        excerpt: 'Tenant shall be responsible for the cost of all routine repairs not exceeding two hundred dollars ($200.00) per incident, including but not limited to plumbing, electrical, and appliance repairs.',
      },
      {
        id: 'c5',
        clause_ref: '15.2',
        title: 'Co-Signer Liability',
        description: 'The co-signer assumes full joint and several liability for all obligations under the lease, including rent, damages, and fees. The co-signer is bound for the entire lease term with no release mechanism.',
        risk_level: 'high',
        source: { page: 11, clause_ref: '15.2' },
        relevant_to: ['co-signer'],
        excerpt: 'Co-Signer hereby assumes joint and several liability for all obligations of Tenant under this Lease, including but not limited to the payment of rent, damages, and fees, for the full term of this Lease.',
      },
    ],
    fullText: [
      { page: 1, clause_ref: '1.0', text: 'This Residential Lease Agreement ("Lease") is entered into between Landlord and Tenant for the property located at Unit 4B, Maple Court.' },
      { page: 2, clause_ref: '3.1', text: 'The monthly rent shall be $2,400, payable on the first day of each calendar month.' },
      { page: 3, clause_ref: '4.2', text: 'If Tenant fails to pay rent within three (3) days of the due date, a late fee of seventy-five dollars ($75.00) shall apply, plus fifteen dollars ($15.00) per additional day, not to exceed five hundred dollars ($500.00) in total.' },
      { page: 5, clause_ref: '7.1', text: 'Landlord may deduct from the security deposit the cost of repairing any damage to the Premises beyond normal wear and tear, including but not limited to painting, cleaning, and replacement of fixtures.' },
      { page: 7, clause_ref: '9.3', text: 'Tenant may terminate this Lease prior to expiration upon sixty (60) days written notice to Landlord, and shall pay a termination fee equal to one (1) month\'s rent.' },
      { page: 9, clause_ref: '12.1', text: 'Tenant shall be responsible for the cost of all routine repairs not exceeding two hundred dollars ($200.00) per incident, including but not limited to plumbing, electrical, and appliance repairs.' },
      { page: 11, clause_ref: '15.2', text: 'Co-Signer hereby assumes joint and several liability for all obligations of Tenant under this Lease, including but not limited to the payment of rent, damages, and fees, for the full term of this Lease.' },
    ],
  },
  {
    id: 'emp-001',
    title: 'Executive Employment Agreement',
    subtitle: 'Confidential // Senior Leadership Compensation Schedule',
    category: 'employment',
    detected_roles: ['executive', 'company', 'board'],
    clauses: [
      {
        id: 'c1',
        clause_ref: '3.1',
        title: 'Base Salary Review',
        description: 'Base salary is set at $350,000 annually, reviewed at the discretion of the Board. There is no guaranteed annual review or minimum increase, meaning compensation may stagnate relative to market rates.',
        risk_level: 'medium',
        source: { page: 2, clause_ref: '3.1' },
        relevant_to: ['executive'],
        excerpt: 'Executive\'s base salary shall be $350,000 per annum, subject to review by the Board of Directors at its sole discretion.',
      },
      {
        id: 'c2',
        clause_ref: '5.2',
        title: 'Severance & Accelerated Vesting',
        description: 'Upon termination without cause, Executive receives 12 months base salary plus accelerated vesting of all unvested equity. This is a strong protective provision for the executive.',
        risk_level: 'low',
        source: { page: 6, clause_ref: '5.2' },
        relevant_to: ['executive', 'company'],
        excerpt: 'In the event of termination without cause, Executive shall receive twelve (12) months of base salary, plus full acceleration of all unvested equity awards.',
      },
      {
        id: 'c3',
        clause_ref: '7.1',
        title: 'Non-Compete Scope',
        description: 'The non-compete restricts the executive from working for any competitor for 18 months post-termination, with no geographic limitation. This is broad and may be unenforceable in jurisdictions that require reasonableness in scope and duration.',
        risk_level: 'high',
        source: { page: 8, clause_ref: '7.1' },
        relevant_to: ['executive', 'company'],
        excerpt: 'Executive shall not, for a period of eighteen (18) months following termination, engage in any business that competes with the Company, regardless of geographic location.',
      },
      {
        id: 'c4',
        clause_ref: '9.3',
        title: 'Board Representation',
        description: 'The executive shall serve on the Board during employment but has no right to board seat designation or observer rights after termination. The company can remove the executive from the board at any time.',
        risk_level: 'medium',
        source: { page: 11, clause_ref: '9.3' },
        relevant_to: ['executive', 'board'],
        excerpt: 'Executive shall serve as a member of the Board of Directors during the term of employment. The Company reserves the right to remove Executive from the Board at any time.',
      },
    ],
    fullText: [
      { page: 1, clause_ref: '1.0', text: 'This Executive Employment Agreement is entered into between the Company and the Executive, effective as of the start date.' },
      { page: 2, clause_ref: '3.1', text: 'Executive\'s base salary shall be $350,000 per annum, subject to review by the Board of Directors at its sole discretion.' },
      { page: 6, clause_ref: '5.2', text: 'In the event of termination without cause, Executive shall receive twelve (12) months of base salary, plus full acceleration of all unvested equity awards.' },
      { page: 8, clause_ref: '7.1', text: 'Executive shall not, for a period of eighteen (18) months following termination, engage in any business that competes with the Company, regardless of geographic location.' },
      { page: 11, clause_ref: '9.3', text: 'Executive shall serve as a member of the Board of Directors during the term of employment. The Company reserves the right to remove Executive from the Board at any time.' },
    ],
  },
  {
    id: 'estate-001',
    title: 'Last Will and Testament',
    subtitle: 'Estate Planning // Revocable Living Trust',
    category: 'estate',
    detected_roles: ['testator', 'beneficiary', 'executor', 'trustee'],
    clauses: [
      {
        id: 'c1',
        clause_ref: '2.1',
        title: 'Distribution of Residuary Estate',
        description: 'The residuary estate is distributed equally among named beneficiaries. If any beneficiary predeceases the testator, their share passes to their descendants per stirpes — this is standard but should be verified against your family structure.',
        risk_level: 'low',
        source: { page: 2, clause_ref: '2.1' },
        relevant_to: ['testator', 'beneficiary'],
        excerpt: 'I give, devise, and bequeath all the rest, residue, and remainder of my estate to my beneficiaries in equal shares, per stirpes.',
      },
      {
        id: 'c2',
        clause_ref: '4.3',
        title: 'Executor Powers',
        description: 'The executor is granted broad powers including the ability to sell, lease, or mortgage real property without court approval. This is common but means the executor has significant discretion over estate assets.',
        risk_level: 'medium',
        source: { page: 5, clause_ref: '4.3' },
        relevant_to: ['executor', 'beneficiary'],
        excerpt: 'My Executor shall have the power, without court order, to sell, lease, or mortgage any real property of my estate at such price and on such terms as my Executor deems appropriate.',
      },
      {
        id: 'c3',
        clause_ref: '6.1',
        title: 'Trustee Succession',
        description: 'If the primary trustee is unable or unwilling to serve, no successor trustee is named. This could require court intervention to appoint a trustee, causing delays and additional expense.',
        risk_level: 'high',
        source: { page: 8, clause_ref: '6.1' },
        relevant_to: ['trustee', 'beneficiary'],
        excerpt: 'If my named Trustee shall fail to qualify or cease to act, no successor Trustee is hereby named, and a court of competent jurisdiction shall appoint a successor.',
      },
      {
        id: 'c4',
        clause_ref: '8.2',
        title: 'No-Contest Clause',
        description: 'Any beneficiary who contests the will forfeits their entire share. This is enforceable in most jurisdictions but may not apply if there is probable cause for the contest.',
        risk_level: 'medium',
        source: { page: 10, clause_ref: '8.2' },
        relevant_to: ['beneficiary'],
        excerpt: 'If any beneficiary under this Will shall contest or object to the probate of this Will, then such beneficiary shall forfeit all interests under this Will.',
      },
    ],
    fullText: [
      { page: 1, clause_ref: '1.0', text: 'I, the Testator, being of sound mind, declare this to be my Last Will and Testament, revoking all prior wills.' },
      { page: 2, clause_ref: '2.1', text: 'I give, devise, and bequeath all the rest, residue, and remainder of my estate to my beneficiaries in equal shares, per stirpes.' },
      { page: 5, clause_ref: '4.3', text: 'My Executor shall have the power, without court order, to sell, lease, or mortgage any real property of my estate at such price and on such terms as my Executor deems appropriate.' },
      { page: 8, clause_ref: '6.1', text: 'If my named Trustee shall fail to qualify or cease to act, no successor Trustee is hereby named, and a court of competent jurisdiction shall appoint a successor.' },
      { page: 10, clause_ref: '8.2', text: 'If any beneficiary under this Will shall contest or object to the probate of this Will, then such beneficiary shall forfeit all interests under this Will.' },
    ],
  },
  {
    id: 'court-001',
    title: 'Notice of Civil Claim',
    subtitle: 'Legal Notice // Case No. CV-2024-0817',
    category: 'court',
    detected_roles: ['plaintiff', 'defendant', 'witness'],
    clauses: [
      {
        id: 'c1',
        clause_ref: '1.3',
        title: 'Response Deadline',
        description: 'The defendant must file a response within 30 days of service. Failure to respond may result in a default judgment being entered against the defendant without further notice.',
        risk_level: 'high',
        source: { page: 1, clause_ref: '1.3' },
        relevant_to: ['defendant'],
        excerpt: 'Defendant must file a written response to this Claim within thirty (30) days of service. Failure to respond may result in entry of default judgment.',
      },
      {
        id: 'c2',
        clause_ref: '3.2',
        title: 'Damages Sought',
        description: 'The plaintiff seeks general damages in excess of $75,000, plus special damages for medical expenses and lost wages, and punitive damages. The total exposure is not capped and could exceed $150,000.',
        risk_level: 'high',
        source: { page: 3, clause_ref: '3.2' },
        relevant_to: ['defendant', 'plaintiff'],
        excerpt: 'Plaintiff seeks general damages in excess of $75,000, special damages for medical expenses and lost wages, and punitive damages in an amount to be determined at trial.',
      },
      {
        id: 'c3',
        clause_ref: '5.1',
        title: 'Witness Disclosure Requirement',
        description: 'All witnesses must be disclosed within 60 days. Failure to disclose may result in the witness being barred from testifying at trial.',
        risk_level: 'medium',
        source: { page: 5, clause_ref: '5.1' },
        relevant_to: ['witness', 'plaintiff', 'defendant'],
        excerpt: 'All parties must disclose all witnesses, including their names and addresses, within sixty (60) days of the scheduling order. Failure to disclose may result in exclusion of the witness at trial.',
      },
    ],
    fullText: [
      { page: 1, clause_ref: '1.3', text: 'Defendant must file a written response to this Claim within thirty (30) days of service. Failure to respond may result in entry of default judgment.' },
      { page: 3, clause_ref: '3.2', text: 'Plaintiff seeks general damages in excess of $75,000, special damages for medical expenses and lost wages, and punitive damages in an amount to be determined at trial.' },
      { page: 5, clause_ref: '5.1', text: 'All parties must disclose all witnesses, including their names and addresses, within sixty (60) days of the scheduling order. Failure to disclose may result in exclusion of the witness at trial.' },
    ],
  },
  {
    id: 'fin-001',
    title: 'Consumer Credit Card Agreement',
    subtitle: 'Financial // Variable Rate — Account Terms',
    category: 'financial',
    detected_roles: ['cardholder', 'issuer'],
    clauses: [
      {
        id: 'c1',
        clause_ref: '2.1',
        title: 'Variable APR',
        description: 'The APR is variable, set at Prime Rate plus 14.99%. With the current Prime Rate of 8.5%, the effective APR is 23.49%. This is high and will increase if the Prime Rate rises.',
        risk_level: 'high',
        source: { page: 2, clause_ref: '2.1' },
        relevant_to: ['cardholder'],
        excerpt: 'The Annual Percentage Rate (APR) for purchases shall be the Prime Rate plus 14.99%, subject to change monthly as the Prime Rate changes.',
      },
      {
        id: 'c2',
        clause_ref: '4.3',
        title: 'Minimum Payment Calculation',
        description: 'The minimum payment is the greater of $35 or 1% of the balance plus interest and fees. Paying only the minimum will result in years of repayment and significant interest costs.',
        risk_level: 'medium',
        source: { page: 4, clause_ref: '4.3' },
        relevant_to: ['cardholder'],
        excerpt: 'The minimum monthly payment shall be the greater of $35.00 or one percent (1%) of the new balance, plus interest charges and any fees assessed.',
      },
      {
        id: 'c3',
        clause_ref: '7.2',
        title: 'Arbitration Clause',
        description: 'Disputes must be resolved through binding arbitration, not court. The cardholder waives the right to participate in class action lawsuits. This limits legal recourse significantly.',
        risk_level: 'high',
        source: { page: 7, clause_ref: '7.2' },
        relevant_to: ['cardholder', 'issuer'],
        excerpt: 'Any dispute arising from this Agreement shall be resolved through binding arbitration. Cardholder waives the right to participate in any class action litigation.',
      },
    ],
    fullText: [
      { page: 2, clause_ref: '2.1', text: 'The Annual Percentage Rate (APR) for purchases shall be the Prime Rate plus 14.99%, subject to change monthly as the Prime Rate changes.' },
      { page: 4, clause_ref: '4.3', text: 'The minimum monthly payment shall be the greater of $35.00 or one percent (1%) of the new balance, plus interest charges and any fees assessed.' },
      { page: 7, clause_ref: '7.2', text: 'Any dispute arising from this Agreement shall be resolved through binding arbitration. Cardholder waives the right to participate in any class action litigation.' },
    ],
  },
];
